name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DLLVM_CREATE_XCODE_TOOLCHAIN=ON
    - name: make
      run: cmake -B ${{github.workspace}}/build
    - name: Update Release
      # You may pin to the exact commit or the version.
      # uses: johnwbyrd/update-release@1d5ec4791e40507e5eca3b4dbf90f0b27e7e4979
      uses: johnwbyrd/update-release@v1.0.0
      with:
        # Your Github token; try \$\{\{ secrets.GITHUB_TOKEN \}\} if your build lasts less than an hour, or create your own secret token with repository access if your build requires longer than an hour.
        token: ${{secrets.GITHUB_TOKEN}}
        # Paths to built files to be released. May be absolute or relative to \$\{\{ github.workspace \}\}.
        files: ${{github.workspace}}/build
        # The name of the release to be created. A reasonable looking release name will be created from the current \$\{\{ github.ref \}\} if this input is not supplied.
        #release: # optional
        # The name of the tag to be used. If not provided, the name of the release will be used.
        #tag: # optional
        # A one-line description for both the tag and the release.
        #message: # optional
        # A fuller description of the release.
        #body: # optional
        # Should the release, if created, be marked as a prerelease?  Such releases are generally publicly visible.
#         prerelease: # optional, default is true
        # Should the release, if created, be marked as a draft?  Such releases are generally not publicly visible.
#         draft: # optional
